name: GitHub Actions Demo
run-name: ${{ github.actor }} is testing out GitHub Actions

on:
  # 每隔XX触发
  schedule:
    - cron: "0 * * * *" 
  
  # 允许手动触发
  workflow_dispatch:

  # push到master分支时触发
  push:
    branches:
      - master

jobs:
  Test-GitHub-Actions:
    runs-on: ubuntu-latest

    permissions: 
      contents: write

    steps:
      # - name: Checkout Respository
      #   uses: actions/checkout@v4
      #   with:
      #     fetch-depth: 0

      # - name: Configure Git
      #   run: |
      #     git config user.name "github-actions[bot]"
      #     git config user.email "github-actions[bot]@users.noreplay.github.com"

      # - name: Switch To Output Branch
      #   run: |
      #     if git ls-remote --heads origin output | grep -q output; then
      #       git checkout output
      #       git pull origin output # 拉最新内容
      #     else
      #       git checkout --orphan output
      #       git rm -rf .
      #     fi

      - name: Create File
        run: |
          echo "- 时间: $(date '+%Y-%m-%d %H:%M:%S')" >> README.md

      # - name: Commit And Push
      #   run: |
      #     git add .
      #     git diff --staged --quiet || git commit -m "Auto-Generate"
      #     git push origin output

      - name: Commit And Push
        uses: crazy-max/ghaction-github-pages@v3.1.0
        with:
          target_branch: output
          build_dir: .
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: "信息"
        run: |
          echo "runner.os:          ${{ runner.os }}"
          echo "github.actor:       ${{ github.actor }}"
          echo "github.event_name:  ${{ github.event_name }}"
          echo "github.ref:         ${{ github.ref }}"
          echo "github.repository:  ${{ github.repository }}"
          echo "github.workspace:   ${{ github.workspace }}"
          echo "job.status:         ${{ job.status }}"

