name: GitHub Actions Demo
run-name: ${{ github.actor }} is testing out GitHub Actions

on:

  # 每24小时触发
  schedule:
    - cron: "0 */24 * * *" 
  
  # 允许手动触发
  workflow_dispatch:

  push:
    branches:
      - master

jobs:
  Test-GitHub-Actions:
    runs-on: ubuntu-latest

    permissions: 
      contents: write

    steps:
      - name: Checkout Respository
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Configure Git
        run: |
          git config user.name "github-actions[bot]"
          git config user.email "github-actions[bot]@users.noreplay.github.com"

      - name: Switch To Output Branch
        run: |
          if git ls-remote --heads origin output | grep -q output; then
            git checkout output
            git pull origin output # 拉最新内容
            git rm -rf .
          else
            git checkout --orphan output
            git rm -rf .
          fi

      - name: Create File
        run: |
          echo "开始测试Cron:" >> README.md

      - name: Commit And Push
        run: |
          git add .
          git diff --staged --quiet || git commit -m "Auto-Generate"
          git push origin output

      - name: "信息"
        run: |
          echo "runner.os:          ${{ runner.os }}"
          echo "github.actor:       ${{ github.actor }}"
          echo "github.event_name:  ${{ github.event_name }}"
          echo "github.ref:         ${{ github.ref }}"
          echo "github.repository:  ${{ github.repository }}"
          echo "github.workspace:   ${{ github.workspace }}"
          echo "job.status:         ${{ job.status }}"

